### ISSUE TITLE
really need this future

### ISSUE THREAD

**Issue by ParsapythonLv** [masterking32/MasterHamsterKombatBot#297] opened 2024-08-31 04:58 UTC
It has been some time since one of my friends requested that card combos should be purchased every day according to the ratio of their income to their cost, and this is really needed, and maybe the amount of their income is sometimes not high, but we will receive a good profit, which is before buying cards.  Profit should take priority with the combo so that all the money is not spent and he can buy Haru cards, also considering that this robot has this capability in it, you can get help from it (written with a translator)❤️
https://github.com/shamhi/HamsterKombatBot

**Comment by tboy1337** [comment] 2024-08-31 11:37
Duplicate of https://github.com/masterking32/MasterHamsterKombatBot/issues/69, please post there about this issue.

**Comment by ParsapythonLv** [comment] 2024-08-31 17:31
> Duplicate of #69, please post there about this issue.

I explained differently

**Closed** 2024-08-31 17:37 UTC
