### ISSUE TITLE
Bot closing itself

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterHamsterKombatBot#459] opened 2024-09-17 09:39 UTC
Woke up this morning and checked the bot at 10am and found it has closed itself in the night.  I run many bots at the same time and I find this every morning, it closed 3 of the bots last night with the same error.

```
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:31 [Account 10]: 🌌 Starting account.
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:31 [Account 10]: 📡 Getting account IP.
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:32 [Account 10]: ├─ IP: xxx.xxx.xxx.xxx
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:32 [Account 10]: ├─ Company: xxx
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:32 [Account 10]: └─ Country: xxx
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:32 [Account 10]: 🛸 Getting basic account data.
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:34 [Account 10]: ├─ Account ID: xxxxxxxxx
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:34 [Account 10]: └─ Account Name: x
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:34 [Account 10]: 🛸 Getting account data.
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:35 [Account 10]: 💰 Account Balance Coins: 58.24m
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:35 [Account 10]: ├─ Available Taps: 4878 | Max Taps: 5000
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:35 [Account 10]: └─ Total Keys: 1218 | Balance Keys: 1218
[Master HamsterKombat Bot][INFO] 2024-09-17 04:34:35 [Account 10]: 📝 Getting account config data.
[Master HamsterKombat Bot][ERROR] 2024-09-17 04:35:06 [Account 10]: ✖ Error: HTTPSConnectionPool(host='api.hamsterkombatgame.io', port=443): Read timed out. (read timeout=30)
```

**Comment by Fy0urM** [comment] 2024-09-17 09:44
Before creating an issue for a bot, first check how the original application feels. it is currently dead

**Comment by rojsedqi** [comment] 2024-09-17 09:51
> Before creating an issue for a bot, first check how the original application feels. it is currently dead

Not dead for everyone, I fear it may be a ban.

**Comment by Fy0urM** [comment] 2024-09-17 09:54
Even if it was a ban, you would get a correct response from the server, but since the connection time is out or you get an incorrect response, it's a problem with the application.

**Comment by Fy0urM** [comment] 2024-09-17 09:56
some new season update, just managed to enter the app once and there was a picture with some new season, didn't realize to take a screenshot.

**Comment by tboy1337** [comment] 2024-09-17 10:05
This issue is happening for me every evening so its not related to the current downtime at least directly but the bot should be able to handle these loss of connection issues and just keep retrying until it connects again, it should never close itself under these circumstances.

**Comment by Fy0urM** [comment] 2024-09-17 10:14
this is new update which broke application again

![image](https://github.com/user-attachments/assets/1e2982d0-5b33-44f8-a0db-6a544f935ba6)

**Comment by Fy0urM** [comment] 2024-09-17 10:16
> This issue is happening for me every evening so its not related to the current downtime at least directly but the bot should be able to handle these loss of connection issues and just keep retrying until it connects again, it should never close itself under these circumstances.

this is already some of your problems, I have bots working 24/7 on both windows and linux and do not encounter the problems that you have

**Comment by tboy1337** [comment] 2024-09-17 11:05
> > This issue is happening for me every evening so its not related to the current downtime at least directly but the bot should be able to handle these loss of connection issues and just keep retrying until it connects again, it should never close itself under these circumstances.
> 
> this is already some of your problems, I have bots working 24/7 on both windows and linux and do not encounter the problems that you have

Its probably not my connection to the internet as its only some of them closing, it could be the connection to the proxy dropping out but I’m using paid ones from the suggested service so there’s not much I can do about that, the bot just needs to be able to deal with connection failures better then it currently does.

**Comment by Fy0urM** [comment] 2024-09-17 11:07
the bot does not stop in case of a connection failure, but continues its execution. there is no message in the log you provided about the bot stopping working due to any problem

**Comment by tboy1337** [comment] 2024-09-17 11:14
Hmm even though it doesn’t say anything in the logs it seems more than a coincidence that it closes after this error, could it be a malformed response from the server is making it close somehow?

**Comment by Fy0urM** [comment] 2024-09-17 11:17
Here is an example of a bot closing due to an unhandled error. 
https://github.com/masterking32/MasterHamsterKombatBot/issues/456#issuecomment-2354852464
Most likely the problem is in your own modification

**Comment by sarqovik** [comment] 2024-09-17 13:35
hello sir, is the bot still safe to use? thanks

**Closed** 2024-09-17 14:02 UTC
